FROM node:24-bookworm-slim

ENV NODE_ENV=development

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json ./
COPY prisma/ ./prisma/

RUN npm install
RUN npx prisma generate

EXPOSE 3001
EXPOSE 5555

CMD ["npm", "run", "start:dev"]
